### ISSUE TITLE
[Cross post from original Repo] Invariant Violation: requireNativeComponent: "RNSketchCanvas" was not found in the UIManager

### ISSUE THREAD

**Issue by claytongroth** [Gigasz/react-native-sketch-canvas#1]
Cross-posting from the original repo seeing as it is likely dead...

I simply have a minimal example of the first code block listed on the repo's NPM page.

I have installed and linked properly. I cannot seem to get around this error.

I am using Expo CLI, if that is relevant.

I believe I have to "Detach" and run with expo kit in order to do anything that requires linking?

![Screenshot_2019-07-03-11-39-11](https://user-images.githubusercontent.com/37966122/60613172-948e2480-9d87-11e9-9b51-362a2d661257.png)

**Comment by Gigasz** [comment]
Yes, that means the library is not linked properly

I'm not familiar with expo, but if it's possible to detach from it and access the native code so you can link manually or via "react-native link @gigasz/react-native-sketch-canvas" i highly recommend it

**Comment by Gigasz** [comment]
I'm closing this issue since it's not a but or a feature request

**Comment by yestay90** [comment]
@Gigasz when using react 61.5 do we still need to link package?
